name: Publish Website

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get Latest Code
        uses: actions/checkout@v3

      - name: 📂 Sync Files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: beats2ursoul.com
          remote-user: dh_zsm733
          private-ssh-key: ${{ secrets.SSH_KEY }}
          destination-path: /home/dh_zsm733/beats2ursoul.com/wp-content/themes/house-music2
